### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vctrfrnndz** [auth0/styleguide#93]
- [ ] Add separate css bundles, core / website / product in addition to the main bundle. This will alow us to only import what is needed for a project.
- [ ] Design playground and documentation for react components.
- [ ] Document react components implementation
- [ ] Bring separate statess ui component from web-header and keep the UI in this project, to be imported in web-header repo
- [ ] Remove al interdependencies in components (most of this is coming from inherited boostrap code).
- [ ] Replace livereload with browsersync in dev task

**Comment by arielger** [comment]
![image](https://cloud.githubusercontent.com/assets/6318057/19816973/efb35be8-9d1f-11e6-9aea-ba589a2ec111.png)

**Comment by vctrfrnndz** [comment]
😍
